### ISSUE TITLE
How to get the credit card grouping values

### ISSUE THREAD

**Issue by Chandrakala14** [CTBConsulting/Card.io-for-Capital-One-vertical-Cards#16]
Hi,

You guys done awesome work. I tried to add my card to the ocre.cpp definitions, but I dont know how to get those credit card groupings. Please guide me.

**Comment by Chandrakala14** [comment]
Is there anyone to help me, I m trying to reach you from past 3 days

**Comment by CTBConsulting** [comment]
Send me a picture of your card and I’ll see if we can give you some direction.

Coley Brown
President, CTB Consulting, inc
Co-Founder, VisionMine.com
Office: 410-275-9108
Linkedin: http://www.linkedin.com/in/coleybrown

**Comment by Chandrakala14** [comment]
thank you for reply

![sbi5](https://user-images.githubusercontent.com/22520432/28614883-e9f31e26-7214-11e7-9e06-bab9eae2e652.jpg)
![sbiatm](https://user-images.githubusercontent.com/22520432/28614884-ea3e117e-7214-11e7-917e-4540ee5d9827.jpg)

**Comment by CTBConsulting** [comment]
Hello Chandrakala
Our code should be successful recognizing the numbers on the yellow card you supplied. I will send you a document that describes how to adjust our source to tell it where to look for the card number on your credit card format. Unfortunately after recognizing the card number the process will still fail our code validation routine. The validation routine uses a United States algorithm to see if the numbers our code has captured are in fact a valid card US number. This validation code is in exposed the source and you can modify or eliminate it.


I suspect that it will be difficult to recognize the data on the blue card. This is because of the complex logo behind the card numbers. We can attempt to upgrade our neural engine to be able to discriminate between the logo and the printed card numbers but I can not guarantee success . The effort to try and upgrade the neural network engine will require sending us at least 4 different sample cards for testing. The cards must include several of the following numbers in the area of the card number that is over the logo.

3, 6, 8, 9, 4

Our effort to try and enhance the recognition will involve several days work and would require a payment of $2,500.

Coley Brown
President, CTB Consulting, inc
Co-Founder, VisionMine.com
Office: 410-275-9108
Linkedin: http://www.linkedin.com/in/coleybrown

**Comment by CTBConsulting** [comment]
See the attached documentation on how to add a new credit card format.


Coley Brown
President, CTB Consulting, inc

**Comment by Chandrakala14** [comment]
Hi,

Thank you for your offer. Can you please share the prebuilt shared libraries of leptonica, tess,png and jpg .so files

**Comment by CTBConsulting** [comment]
Hi:
What you are looking for is all under lib-src. We do not maintain that code (except for the build script). Ee just compile it for the target platform. 

Coley

**Comment by Chandrakala14** [comment]
Hi Coley,
I was followed all the instructions as in the document, but I am getting error as

D:/card.io-Android-source/card.io/src/main/jni/card.io-dmz/scan/scan.h:49:3: error: typedef redefinition with different
      types ('struct ScannerState' vs 'struct ScannerState')
} ScannerState;
  ^
D:/card.io-Android-source/card.io/src/main/jni/card.io-dmz/dmz.h:39:29: note: previous definition is here
typedef struct ScannerState ScannerState;

Please help me to solve this.

**Comment by Chandrakala14** [comment]
Hi can anyone suggest the solution
