### ISSUE TITLE
Unknown type name 'namespace'

### ISSUE THREAD

**Issue by safwanmalik** [CTBConsulting/Card.io-for-Capital-One-vertical-Cards#2]
I'm getting 3 error as below when compile the project after follow the step and all in the same file. Can somebody assist me where I do wrong ? or can somebody try it and share if successfully compile everything for reference.

- ../card.io-iOS-source-master/dmz/Eigen/src/Core/util/Macros.h:179:5: Unknown type name 'namespace'
- ../card.io-iOS-source-master/dmz/Eigen/src/Core/util/Macros.h:179:20: Expected ';' after top level declarator
- ../card.io-iOS-source-master/dmz/Eigen/Core:28:10: 'complex' file not found

**Comment by CTBConsulting** [comment]
safwanmalik:
We will be back to you in a bit with an answer to your issue...

**Comment by kevinmfree** [comment]
Coley, I think I know what he is referring to. This happens when xcode
tries to compile objective c++ as objective c. Those card.io files are
objective c++ (the DMZ)  and he is trying to compile them as objective c,
where namespace does not exist. It happens by default when opening thier
source code and they don't explain how to fix it. I will have to go double
check my configuration. But it's the xcode compiler not being configured
properly. I do not have time at the moment though.

**Comment by CTBConsulting** [comment]
I think we are know what you are referring to. This can happen when xcode
tries to compile objective c++ as objective c. The repository card.io files are
objective c++ (the DMZ) and I think you may be trying to compile them as objective c.
In objective c namespace do not exist. It happens by default when opening the
source code and they don't explain how to fix it. We will double
check our configuration but think your issue is probably the xcode compiler not being configured
properly.

**Comment by safwanmalik** [comment]
As per instruction inside the document, dmz should be extract into card.io dmz folder. It should cause dmz to inherited compile setting set for card.io which added into Teserract project. I have the same thought before this cause by the mixed of different compile setting in each project, and try to fixed it with no success.

**Comment by CTBConsulting** [comment]
safwanmalik 
We have a solution that should work for you. We have uploaded an updated version to the master branch. "See updated file "Environment Configurations.pdf" that is now in the master directory at:

https://github.com/CTBConsulting/Card.io-for-Capital-One-vertical-Cards/blob/master/Environment%20Configurations.pdf

This updated procedure list should fix your issue.
